// Creating the very first user on the DB
# POST http://localhost:5000/api/v1/services/createUser
# Content-Type: application/json

# {"initPwd": "random"}

// Setting up the credentials of the very first user on the DB
POST http://localhost:5000/api/v1/services/createCreds HTTP/1.1
Content-Type: application/json
Accept: */*

{
    "newPassword": "random"
}
